# Eat Safe, Love

## Notebook Set Up

In [2]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [3]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [4]:
# List the available databases
print(mongo.list_database_names())

['admin', 'classDB', 'config', 'fruits_db', 'local', 'met', 'santosh_db', 'travel_db', 'uk_food']

In [5]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [6]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [7]:
# assign the collection to a variable
establishments = db['establishments']

In [8]:
# Find and display one document in the establishments collection
result = db.establishments.find_one()
pprint(result)

{'AddressLine1': 'East Cliff Pavilion',
 'AddressLine2': 'Wear Bay Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'The Pavilion',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'ChangesByServerID': 0,
 'Distance': 4591.765489457773,
 'FHRSID': 1043695,
 'LocalAuthorityBusinessID': 'PI/000073616',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CT19 6BL',
 'RatingDate': '2018-04-04T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65fa9bbd66ba3a9fda336737'),
 'geocode': {'latitude': 0.0, 'longitude': 0.0},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/1043695',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 5}}

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [9]:
# Find the establishments with a hygiene score of 20
query =  db.establishments.find({"scores.Hygiene": 20})

# Use count_documents to display the number of documents in the result
count_documents = db.establishments.count_documents({"scores.Hygiene": 20})
print("Number of establishments with a hygiene score of 20:", count_documents)


# Display the first document in the results using pprint
first_document = query[0]
pprint(first_document)

Number of establishments with a hygiene score of 20: 41
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('65fa9bbd66ba3a9fda338269'),
 'geocode': {'latitude': 0.0, 'longitude': 0.0},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [10]:
# Convert the result to a Pandas DataFrame
df = pd.DataFrame(list(query))

# Display the number of rows in the DataFrame
num_rows = len(df)
print("Number of rows in the DataFrame:", num_rows)

# Display the first 10 rows of the DataFrame
first_10_rows = df.head(10)
first_10_rows

Number of rows in the DataFrame: 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,65fa9bbd66ba3a9fda338269,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,65fa9bbd66ba3a9fda3385ee,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,65fa9bbd66ba3a9fda3388f9,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,65fa9bbd66ba3a9fda338ae0,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,65fa9bbd66ba3a9fda338af3,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,65fa9bbd66ba3a9fda33948f,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,65fa9bbd66ba3a9fda3396b2,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,65fa9bbe66ba3a9fda33abe1,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,http://www.rochford.gov.uk,customerservices@rochford.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,65fa9bbe66ba3a9fda33b027,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,http://www.sevenoaks.gov.uk/,environmental.health@sevenoaks.gov.uk,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,65fa9bbe66ba3a9fda33b835,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,http://www.basildon.gov.uk,ehs@basildon.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.0, 'latitude': 0.0}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [11]:
query = {
    "LocalAuthorityName": "London",
    "RatingValue": {"$gte": 4}
}

results = db.establishments.find(query)

for result in results:
    pprint(result)

In [12]:
# Create a DataFrame from the 'data' list
df = pd.DataFrame(query)

# Display the number of rows in the DataFrame
num_rows = len(df)
print("Number of rows in the DataFrame:", num_rows)

# Display the DataFrame
print(df)

Number of rows in the DataFrame: 1
     LocalAuthorityName  RatingValue
$gte             London            4

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [13]:
from decimal import Decimal

# Geocode coordinates of Penang Flavours
penang_longitude = Decimal("0.08384000")
penang_latitude = Decimal("51.49014200")

# Find the top 5 establishments with RatingValue of 5, sorted by lowest hygiene score and nearest to Penang Flavours
top_establishments = establishments.find(
    {
        "RatingValue": 5,
        "scores.Hygiene": {"$ne": ""},
        "geocode.longitude": {"$exists": True},
        "geocode.latitude": {"$exists": True}
    },
    {
        "BusinessName": 1,
        "RatingValue": 1,
        "scores.Hygiene": 1,
        "geocode.longitude": 1,
        "geocode.latitude": 1
    }
).sort([
    ("scores.Hygiene", 1),
    ("geocode.longitude", 1),
    ("geocode.latitude", 1)
]).limit(5)

# Display the top 5 establishments
for idx, establishment in enumerate(top_establishments, 1):
    print(f"Top {idx} Establishment:")
    pprint(establishment)

Top 1 Establishment:
{'BusinessName': 'The Lifeboat',
 'RatingValue': 5,
 '_id': ObjectId('65fa9bbd66ba3a9fda336782'),
 'geocode': {'latitude': 0.0, 'longitude': 0.0},
 'scores': {'Hygiene': None}}
Top 2 Establishment:
{'BusinessName': 'Lucky Chip',
 'RatingValue': 5,
 '_id': ObjectId('65fa9bbd66ba3a9fda3367ac'),
 'geocode': {'latitude': 0.0, 'longitude': 0.0},
 'scores': {'Hygiene': None}}
Top 3 Establishment:
{'BusinessName': 'Sweet Rendezvous',
 'RatingValue': 5,
 '_id': ObjectId('65fa9bbd66ba3a9fda3367a7'),
 'geocode': {'latitude': 0.0, 'longitude': 0.0},
 'scores': {'Hygiene': None}}
Top 4 Establishment:
{'BusinessName': 'Harbour Inn',
 'RatingValue': 5,
 '_id': ObjectId('65fa9bbd66ba3a9fda336776'),
 'geocode': {'latitude': 0.0, 'longitude': 0.0},
 'scores': {'Hygiene': None}}
Top 5 Establishment:
{'BusinessName': 'Little Rock',
 'RatingValue': 5,
 '_id': ObjectId('65fa9bbd66ba3a9fda336747'),
 'geocode': {'latitude': 0.0, 'longitude': 0.0},
 'scores': {'Hygiene': None}}

In [22]:
from decimal import Decimal

# Convert Decimal to float for latitude and longitude
penang_longitude = float(Decimal("0.08384000"))
penang_latitude = float(Decimal("51.49014200"))
latitude_range = 0.01
longitude_range = 0.01

# Find the establishments within the latitude and longitude range
top_establishments = establishments.find(
    {
        "RatingValue": 5,
        "scores.Hygiene": {"$ne": ""},
        "geocode.longitude": {
            "$gte": penang_longitude - longitude_range,
            "$lte": penang_longitude + longitude_range
        },
        "geocode.latitude": {
            "$gte": penang_latitude - latitude_range,
            "$lte": penang_latitude + latitude_range
        }
    },
    {
        "BusinessName": 1,
        "RatingValue": 1,
        "scores.Hygiene": 1,
        "geocode.longitude": 1,
        "geocode.latitude": 1
    }
).sort([
    ("scores.Hygiene", 1),
    ("geocode.longitude", 1),
    ("geocode.latitude", 1)
]).limit(20)

# Display the establishments with pretty printing
for establishment in top_establishments:
    pprint(establishment)

In [15]:
# Convert result to Pandas DataFrame

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [35]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest
pipeline = [
    { '$match': { 'scores.Hygiene': 0 } },  # Match establishments with a hygiene score of 0
    { '$group': { '_id': '$LocalAuthorityName', 'count': { '$sum': 1 } } },  # Group by Local Authority
    { '$sort': { 'count': -1 } }  # Sort the matches from highest to lowest count
]

result = list(db.establishments.aggregate(pipeline))

# Print the number of establishments with a hygiene score of 0
print("Number of establishments with a hygiene score of 0:", sum(doc['count'] for doc in result))

# Print the top 10 Local Authorities with the highest count of establishments with a hygiene score of 0
for idx, doc in enumerate(result[:10]):
    print(f"Local Authority: {doc['_id']}, Count: {doc['count']}")

Number of establishments with a hygiene score of 0: 16827
Local Authority: Thanet, Count: 1130
Local Authority: Greenwich, Count: 882
Local Authority: Maidstone, Count: 713
Local Authority: Newham, Count: 711
Local Authority: Swale, Count: 686
Local Authority: Chelmsford, Count: 680
Local Authority: Medway, Count: 672
Local Authority: Bexley, Count: 607
Local Authority: Southend-On-Sea, Count: 586
Local Authority: Tendring, Count: 542

In [38]:
# Convert the result to a Pandas DataFrame
# Convert the MongoDB aggregation result to a Pandas DataFrame
df = pd.DataFrame(result)

# Print the Pandas DataFrame
print(df)

                           _id  count
0                       Thanet   1130
1                    Greenwich    882
2                    Maidstone    713
3                       Newham    711
4                        Swale    686
5                   Chelmsford    680
6                       Medway    672
7                       Bexley    607
8              Southend-On-Sea    586
9                     Tendring    542
10                  Colchester    498
11             Tunbridge Wells    491
12        Folkestone and Hythe    480
13                  Eastbourne    478
14                    Hastings    464
15                     Bromley    460
16                     Ashford    427
17                    Havering    397
18                    Dartford    383
19                   Braintree    382
20                    Basildon    362
21                   Gravesham    339
22       Tonbridge and Malling    325
23                    Thurrock    313
24        Barking and Dagenham    301
25             Canterbury City    298
26                   Brentwood    285
27                Castle Point    281
28                      Harlow    274
29                  Uttlesford    251
30                       Lewes    250
31                   Sevenoaks    223
32                      Maldon    197
33          East Hertfordshire    189
34                    Rochford    187
35                   Redbridge    182
36               Epping Forest    180
37                East Suffolk    159
38              Waltham Forest    110
39                     Babergh     97
40                     Wealden     93
41                      Rother     80
42                    Lewisham     65
43                   Tandridge     42
44  City of London Corporation     28
45                     Ipswich     21
46               Tower Hamlets      9
47         North Hertfordshire      6
48                  Mid Sussex      5
49                     Reading      1
50                      Dorset      1
51                  Sunderland      1
52               North Norfolk      1
53      Kensington and Chelsea      1
54                  Broxbourne      1

In [39]:
# Display the number of rows in the DataFrame
num_rows = df.shape[0]

# Display the first 10 rows of the DataFrame
print(df.head(10))

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542